spring:
  application:
    name: webflux
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/webflux
    username: root
    password: root
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate.format_sql: true

server:
  port: 8081

